spring:
  application:
    name: sgc-proveperu

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # none = no hace nada, update = actualiza el esquema, create = crea el esquema, create-drop = crea el esquema y lo borra al finalizar
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: America/Lima
    show-sql: false

server:
  port: ${BACKEND_PORT:8080}

# JWT
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-ms: ${JWT_EXPIRATION_MS:28800000}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.proveperu: INFO